language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: tRYIonq9YWDonRRgEtMHNI2z8tl4kJC7lobOzA9Qj6dNRmKePdY9c/+vwz4QsPhy9h1LA1UMTgMNytZWg1KcfFbzAbK1/AwkHm/xlwNrKhE6TuXd+R8itdo9hU2wKT3gXuOcjiYRsAjScf97OyC0MsbQ7KkcVh0tv1NpyRNG2LiZKeoUQOMndKV4fpTKEfA4GWrJ3FZC3z9rUEHMSCc0lAqqCgD1zYlQU2k0baedQLunWUxMdKaQOMPZ0N2Gs3WaFe2aYOh0ftiP1XLiSPZ5OR0cHVyuE4rZ3WWfOFI6eogq1A+VTphmhC+RnOT23FN6ZiFSCTYNeCT0SA9hZx7rVm9tvrCNbRfNL3Qr1LD043zJMj0IhkGun+Dws06aqjgNgwiFFCHjqq+ENxTZ+JQ2889ZaYUq7mhXWM1sT0vs7lhHjJPMUy1AAe/ONEJf3ABwXsQejFzKokU6iYCFSD2g7fIAIiQ2oPlyUO1hB5cKYl7Jxihek04KpQsgcOvlCrYKNO9RAMON9UHPdAIF7+aWYN585uJlk0Rh5KD+wmKnepCfZjHkVHJ1qdTr7vaH+bvRO6R12hrx8xg/Z8RdP60jxHB3FFz0k006SiQaExheV4sv3guIn4+XNS/dfQs6lQ9+wr6mt2Zk18RAhxFf09iZOvqVuXrHzjWsIj72Hd2xGZM=
  app: textbottle
  on:
    repo: jsphkm/Textbottle
  services: mongodb
